# Generated by Django 4.2.5 on 2023-11-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
